---
stages:
  - initialize

Setup_Clients_Env:
  stage: initialize
  image:
    name: almalinux:8
  script:
    # Enable PowerTools/CRB repository for additional packages
    - dnf install -y epel-release
    - dnf config-manager --set-enabled powertools
    # Add Docker CE repository
    - dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    # Install required packages
    - dnf install -y ansible docker-ce-cli python3-pip containerd.io
    # Verify installations
    - docker version
    - ANSIBLE_CONFIG=./ansible.cfg ansible --version
    - ANSIBLE_CONFIG=./ansible.cfg ansible all -i hosts -c docker -m ping
    - ANSIBLE_CONFIG=./ansible.cfg ansible-playbook -i hosts -c docker site.yml
  tags:
    - docker
