---
- name: Configure all hosts with basic setup
  hosts: all
  gather_facts: false
  tasks:
    - name: Install SSH and sudo packages
      dnf:
        name: '{{ item }}'
        state: latest
      loop:
        - openssh-server
        - openssh-clients
        - sudo

    - name: Start and enable sshd service
      systemd:
        name: sshd
        state: started
        enabled: true

    - name: Disable getty services
      systemd:
        name: '{{ item }}'
        state: stopped
        masked: true
      with_items:
        - getty@tty1.service
        - serial-getty@ttyS0.service

    - name: Create vagrant group
      group:
        name: vagrant
        state: present

    - name: Create vagrant user
      user:
        name: vagrant
        groups: vagrant,wheel

    - name: Create vagrant SSH directory
      file:
        path: /home/vagrant/.ssh
        state: directory
        mode: '0700'
        owner: vagrant
        group: vagrant

    - name: Copy SSH authorized keys
      copy:
        src: authorized_keys
        dest: /home/vagrant/.ssh/authorized_keys
        mode: '0644'
        owner: vagrant
        group: vagrant

    - name: Add vagrant to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^vagrant\s'
        line: 'vagrant ALL=(ALL) NOPASSWD: ALL'

- name: Configure console host with development tools
  hosts: consoles
  gather_facts: true
  tasks:
    - name: Install development tools
      dnf:
        name: '{{ item }}'
        state: latest
      loop:
        - vim
        - which
        - tree
        - git
        - epel-release

    - name: Install Ansible for AlmaLinux 8
      dnf:
        name: ansible
        state: present

    - name: Start and enable sshd service on console
      systemd:
        name: sshd
        state: started
        enabled: true

    - name: Create Vagrant machine directories
      file:
        path: '/home/vagrant/vagrant/infraci/.vagrant/machines/{{ item }}/virtualbox'
        state: directory
        mode: '0700'
        owner: vagrant
        group: vagrant
      loop:
        - gitlab
        - gitlab-runner
        - ketchup
        - ketchup-nginx
        - test-ketchup
        - test-ketchup-nginx

    - name: Copy private keys for Vagrant machines
      copy:
        src: private_key
        dest: '/home/vagrant/vagrant/infraci/.vagrant/machines/{{ item }}/virtualbox/private_key'
        mode: '0600'
        owner: vagrant
        group: vagrant
      loop:
        - gitlab
        - gitlab-runner
        - ketchup
        - ketchup-nginx
        - test-ketchup
        - test-ketchup-nginx

    - name: Copy vim configuration
      copy:
        src: vimrc
        dest: '/home/vagrant/.vimrc'
        mode: '0755'
        owner: vagrant
        group: vagrant

    - name: Create SSH directory for vagrant user
      file:
        path: /home/vagrant/.ssh
        state: directory
        mode: '0700'
        owner: vagrant
        group: vagrant

    - name: Copy SSH private key
      copy:
        src: private_key
        dest: /home/vagrant/.ssh/infraci
        mode: '0600'
        owner: vagrant
        group: vagrant
